#!/bin/bash

#SBATCH --job-name=reacher_ppo_trial_gpu
#SBATCH -n 1
#SBATCH --gpus=gtx_1080_ti:1
#SBATCH --cpus-per-task=4
#SBATCH --time=4:00:00
#SBATCH --mem-per-cpu=2048
#SBATCH --output="./log/reacher_ppo_gpu/reacher/spring/stdout.log"
#SBATCH --error="./log/reacher_ppo_gpu/reacher/spring/stderr.log"
#SBATCH --mail-type=BEGIN,END

module load gcc/8.2.0 python_gpu/3.10.4 eth_proxy
module load cuda/11.4.2 cudnn/8.2.1.32

# activate env
source ./.tw/bin/activate
export JAX_PLATFORMS='cuda'
# export XLA_FLAGS='--xla_force_host_platform_device_count=32'  # should be the same as -n above

# run experiment
./.tw/bin/python ./script/training.py ./config/reacher_gpu.gin

